version: '3'
services:
  munro-library:
    image: maven:3-amazoncorretto-11
    command: mvn spring-boot:run
    working_dir: /usr/src/mymaven
    ports:
      - 8880:8080
      - 8081:8081
    volumes:
      - ${PWD}:/usr/src/mymaven
      - ${HOME}/.m2:/root/.m2